### ISSUE TITLE
Fatal error with WP Rocket after latest update

### ISSUE THREAD

**Issue by alfonso100** [WPDreams/ajax-search-pro-development#150] opened 2024-08-07 18:23 UTC
### Describe the bug
hey there 👋 
I'm from WP Rocket support team, we are getting reports from our users that they are getting fatal errors when using **Ajax Search Pro** and **WP Rocket.** 

In this recent update:
https://changelog.ajaxsearchpro.com/#id-4.26.14-2024-08-05

Includes a related change to apply compatibility with caching plugins like WP Rocket to stop them from combining their JS files:
https://github.com/wpdreams/ajax-search-pro-development/issues/143

Based on the error logs, you are trying to pass a value `asp-(.*).js`  to our filter to exclude scripts from being combined. But it seems you are using the wrong filter in **/ajax-search-pro/includes/classes/Hooks/FiltersManager.php:238** : 
`pre_get_rocket_option_exclude_js` is not correct to disable/enable the feature. and it expects a true/false

it would be best if you used **rocket_exclude_defer_js** instead 
https://github.com/wp-media/wp-rocket/blob/961f78501527775c9cc22b6f284cdcf31f9048f6/inc/Engine/Optimization/DeferJS/DeferJS.php#L206

This is the error:
`[2024-08-07T15:25:55.660315+00:00] PHP Fatal error:  Uncaught TypeError: WP_Rocket\Engine\Optimization\DeferJS\Subscriber::exclude_jquery_combine(): Argument #1 ($excluded_files) must be of type array, string given, called in /wp-includes/class-wp-hook.php on line 324 and defined in /wp-content/plugins/wp-rocket/inc/Engine/Optimization/DeferJS/Subscriber.php:73#012Stack trace:#012#0 /wp-includes/class-wp-hook.php(324): WP_Rocket\Engine\Optimization\DeferJS\Subscriber->exclude_jquery_combine('asp-(.*).js')#012#1 /wp-includes/plugin.php(205): WP_Hook->apply_filters('asp-(.*).js', Array[...]`

### To Reproduce
1. Enable the last version of **Aax Search Pro**, and the **WP Rocket**.
2. See the fatal error

### Expected behavior
To exclude a set of files from the value should be filtered at `rocket_exclude_defer_js`. Here is an example: 
https://github.com/wp-media/wp-rocket-helpers/blob/e90b1ed20517ca679e122bca78686346ad6c124e/static-files/wp-rocket-static-exclude-defer-js/wp-rocket-static-exclude-defer-js.php#L35

### Environment checklist
- [ ] This bug happens with only Ajax Search Pro plugin active
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

**Comment by ernestmarcinko** [comment] 2024-08-08 05:57
Hi,

Thank you so much for letting us know, you are amazing! I assumed that filter was used to define the exclusions as it seemed to work, but I was wrong.

Does `pre_get_rocket_option_exclude_js` also exclude from minification? The issue is not the js combine, but the minify step. If so, then I'm going to make the change asap.

All the best,
Ernest

**Comment by joejoe04** [comment] 2024-08-08 12:58
Hi Ernest! Thanks very much for working on this!

To exclude files from JS Minification, please use the `rocket_exclude_js` filter:
https://github.com/wp-media/wp-rocket/blob/961f78501527775c9cc22b6f284cdcf31f9048f6/inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php#L69

You can use it similarly to how Alfonso mentioned in this example, just with the above filter instead:
https://github.com/wp-media/wp-rocket-helpers/blob/e90b1ed20517ca679e122bca78686346ad6c124e/static-files/wp-rocket-static-exclude-defer-js/wp-rocket-static-exclude-defer-js.php#L35

**Comment by ernestmarcinko** [comment] 2024-08-08 19:57
Okay, sounds great! Can I specify regular expressions within `rocket_exclude_js` just like in the plugin options?
I'm asking because the plugin generates bundles based only on required options and the filenames are hashed.

I noticed on a client's website that adding `asp-(.*).js` under the excluded javascript files solved the issue, which is fantastic. Can I also do that here?
I have no copy of WP Rocket so I'm not able to test unfortunately. The best I can do is guess and try on a client's website.

**Comment by joejoe04** [comment] 2024-08-09 07:39
Hi,

Yes, you can use regular expressions. The one you suggested would work, but might come with some minor risk of making false positive matches with other scripts.

Checking some sites reporting this issue, it seems like the scripts come in something like the following format:

`/wp-content/cache/asp/asp-89d7b4cb.min.js`

Is this correct?

If so, maybe you could go with something a little more specific like this:

`/asp/asp-(.*).js`

Just a suggestion. You can decide what regex is best to use.

**Comment by ernestmarcinko** [comment] 2024-08-09 08:07
Fantastic!

Good call. In some cases the file locations are different (where the cache folder does not exist or it has wrong permissions etc..), but I can probably handle that with a more specific regex or with multiple rules.

Is there a way for me to test this - perhaps a sandbox environment with your plugin installed or some other way? I don't need a license per se, just want to be sure the solution works to prevent further complications. Let me know.

**Comment by joejoe04** [comment] 2024-08-09 18:16
Yes, I've created a test site for you with WP Rocket installed so you can use it for testing.

I've sent you an email with the details.

**Comment by ernestmarcinko** [comment] 2024-08-10 11:49
> Yes, I've created a test site for you with WP Rocket installed so you can use it for testing.
> 
> I've sent you an email with the details.

Thank you, got it, it's exactly what I was hoping for!

**Comment by ernestmarcinko** [comment] 2024-08-10 12:38
I have merged a possible solution, the baseline is using the `rocket_exclude_js` and aslo `rocket_excluded_inline_js_content` hooks as the corresponding inline js also needs to be excluded to work properly.

The `is_null` and `is_array` checks are likely unneccessary in both cases and could be replaced with typed parameters, but I like to be prepared for the worst case scenarios :)

It's not the full code, but the hooks look like this:

```php
add_filter(
	'rocket_exclude_js',
	function ( $handles ) {
		$rules = array(
			'/asp/asp-(.*).js',
			'/ajax-search-pro/(.*)/asp-(.*).js',
		);
		if ( is_null($handles) ) {
			return $rules;
		}
		if ( is_array($handles) ) {
			return array_merge($handles, $rules);
		}
		return $handles;
	}
);

add_filter(
	'rocket_excluded_inline_js_content',
	function ( $handles ) {
		$rules = array(
			'ajax-search-pro',
		);
		if ( is_null($handles) ) {
			return $rules;
		}
		if ( is_array($handles) ) {
			return array_merge($handles, $rules);
		}
		return $handles;
	}
);
```

I stress tested this on the temporary website as much as I could, but seems to work all right in every case. If you don't see anything strange, I will push the release as soon as I can.

**Comment by ernestmarcinko** [comment] 2024-08-12 12:08
Plugin version 4.26.15 had been released, updating should hopefully resolve the issue.

**Closed as completed** 2024-08-12 12:08 UTC
Labels: bug

**Comment by joejoe04** [comment] 2024-08-12 12:36
Sorry for the delay, we're mostly off during weekends.

Looks good to me. I'll begin recommending the update if we get any more reports of this.

Thank you!
