### ISSUE TITLE
Search Functionality and Image Display Issues After Latest Plugin Update using Ajax Search Pro

### ISSUE THREAD

**Issue by Minga82** [WPDreams/ajax-search-pro-development#145] opened 2024-08-02 16:09 UTC
After the latest update, the plugin on my website no longer works for searches. When I enter content into the search bar, the search does not start at all. Additionally, all images disappeared from the site, and the module stopped working. Disabling the plugin returned the site to its normal appearance.
To Reproduce

-     Go to the website homepage.
-     Click on the search bar.
-     Enter any content into the search bar.
-     See that the search does not start.

Expected behavior

I expected the search functionality to work correctly when entering content into the search bar and for all images to be displayed normally on the site.

Screenshots - see attachment.
![Screenshot 2024-08-02 180721](https://github.com/user-attachments/assets/a208f22d-156e-46c6-9a22-ad036d2551f5)

**Comment by Minga82** [comment] 2024-08-02 16:38
Hi Ernest, we had a quick chat via comment on Codecanyon - I use WP-Rocket as Cache-Plugin.
BR
Carlo

**Comment by ernestmarcinko** [comment] 2024-08-03 11:41
Hi Carlo,

Please check the response on codecanyon conversation. This is also a duplicate of known issue #143 
I will close this issue, and continue on #143

**Comment by ernestmarcinko** [comment] 2024-08-03 11:42
To add the solution here:

Please add this to the Excluded Javascript Files input:

```
asp-(.*).js
```

Like so: https://imgur.com/mQ4OVF4

**Closed as completed by ernestmarcinko** 2024-08-03 11:41 UTC
Labels: bug
