### ISSUE TITLE
The plugin does not work after updating to version 4.26.13

### ISSUE THREAD

**Issue by kroix** [WPDreams/ajax-search-pro-development#143] opened 2024-08-01 16:16 UTC
### Describe the bug
The plugin does not work (default WP search also doesn't work) and illustrations are not displayed on the site when the plugin is enabled after updating Ajax Search Pro to version 4.26.13. Only background and banners are displayed from the images.
If you disable the plugin, all illustrations are returned.

### To Reproduce
1. Go to Plugins -> Installed 
2. Click on Ajax Search Pro —> Activate
3. See error
4. Click on Ajax Search Pro —> Deactivate
5. No error 

### Expected behavior
Displaying illustrations on the site, as before, the search plugin works.

### Environment checklist
- [x] This bug happens with only Ajax Search Pro plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

### Desktop (please complete the following information):
 - OS: [Windows 11 (x64)
 - Browser [Chrome, Opera, Firefox]
 - Version [127.0.6533.88]

### Smartphone (please complete the following information):
 - Device: [Xiaomi 11T]
 - OS: [Android 14]
 - Browser [Chrome]
 - Version [127.0.6533.65]

### Additional context
![BelVaping - Google Chrome Ajax Search Pro off](https://github.com/user-attachments/assets/4a79eace-e359-46e9-b837-218eaebaa96e)
![BelVaping - Google Chrome Ajax Search Pro on](https://github.com/user-attachments/assets/7d23b8e2-f30d-4326-8399-91dd940eeaff)
![photo_2024-08-01_19-10-19](https://github.com/user-attachments/assets/43b1df9f-d718-49de-b203-14be921b1664)
![Плагины ‹ BelVaping — WordPress - Google Chrome](https://github.com/user-attachments/assets/6d52d015-120f-44ec-872f-ad687fa57dae)
]

**Comment by exetico** [comment] 2024-08-02 11:54
I can confirm the same.

There's a problem around `D.trigger.apply(m, [R].concat(l)),` in the cache file `asp-*.js`, which does crash our whole JavaScript bundled file, too.

![image](https://github.com/user-attachments/assets/17ad3c7c-89e0-42fb-96eb-d10c25712c4b)

![image](https://github.com/user-attachments/assets/666b9b2f-6f3c-40df-815e-eb2259dc5c33)

This needs to be prioritized.

Could sounds like something related to #133 . For that kind of change, I'd personally recommend a beta-release, before pushing out a release to all users.

After checking the docs, wp-dreams in general, codecanyon, the plugin and more, I've not managed to find a way to downgrade the plugin. That's crazy by itself. Have I missed somthing?
I even checked the source-code, but it does nok look like I'm able to query a specific version of ASP to the `https://update.wp-dreams.com/` endpoint, just to see how it did go. I'm only able to request a short lived download link, where I can't find any hints on how I could force another version to be served, instead.

**Comment by ernestmarcinko** [comment] 2024-08-02 12:44
The files are all right, it's the additional minification by cache plugins. We use a esbuild now, which is a different bundler. I just tested WPRocket and W3TC minifiers, they both fail during minification of the already minified source files.

The issue can be resolved by excluding the files from minify:

`asp-(.*).js`

or by changin the source to non-minified:

![image](https://github.com/user-attachments/assets/cca46fa0-2b60-455d-80c8-300000a167c5)

There is always a beta test, if you want, you can both join [via this link](https://ajaxsearchpro.com/development-roadmap-beta-testing/), you are more than welcome.

Nevertheless I'm looking into this to see if I can add programmatical exceptions for already minified sources.

**Comment by kroix** [comment] 2024-08-02 12:59
Hi Ernest, 
Thanks for your tips, but with Ajax Search Pro  4.26.13 & W3 Total Cache: 
1) can be resolved by excluding the files from minify: asp-(.*).js
2) changin the source to non-minified (Javascript source not minified)

![Ajax Search Pro ‹ BelVaping — WordPress - Google Chrome](https://github.com/user-attachments/assets/8679d270-5351-4d76-a72f-886a0d36751d)
![Минификация  W3 Total Cache ‹ BelVaping — WordPress - Google Chrome](https://github.com/user-attachments/assets/8819f949-39d7-4f03-94f2-846671e3200a)

Both don't work.

Completely disabling JavaScript caching minification helped.

![Минификация  W3 Total Cache ‹ BelVaping — WordPress - Google Chrome1](https://github.com/user-attachments/assets/d09e13b6-a65f-4045-8abd-7c0397cc7a81)

**Comment by exetico** [comment] 2024-08-02 13:09
Changing to "non minified" version in the panel, still won't play nice with a normal JavaScript bundled file. I'd also like to confirm that I removed the cached ack-*.js files in mh cache dir before testing it. 

(_Extra feedback 1: Consider flushing the asp file cache, after a user jump from non-minified, to minified, and vice versa._)

Here's the problem, and the result after I use Litespeed cache's Page optimizer, where most scripts are merged into one:
![image](https://github.com/user-attachments/assets/204f5a42-996b-44fc-a4d8-4c19ea58ad00)

It's around here, if I disable the bundled JS optimization in my env:
![image](https://github.com/user-attachments/assets/894c207b-24c3-4a82-861f-0576412246fc)
_And yes, ofc it works without having it bundled with my other scripts :-)._

So something needs to be done, as it's not able to be bundled up anymore, at least with LiteSpeed Cache.

(_Extra feedback 2: Also, switching builder/compiler/bundle stack, should **at least** be a minor version bump, **not** only a patch bump._)

**Comment by ernestmarcinko** [comment] 2024-08-02 13:25
Bundling/Concat seems to work all right on my end, as long as the source is not going through a minify process again - that's where the problems start as the files are already minified. Non-minified is okay-ish, but it's not the solution.

One thing I have noticed is by renaming all minified sources to `.min.js` from `.js` seems to resolve all issues. W3TC simply ignores the minify step when noticing the `.min` in the file name. Whenever they are concatenated at the end should make no difference as they are loaded up in the same order. As long as there is no extra minify step and the file contents are untouched all will be fine.

Excluding the files from the minify step programmatically or manually is the only possible solution here. Let me test other cache plugins to see if `.min` does the trick. It makes sense.

**Comment by exetico** [comment] 2024-08-02 13:28
Did you check the "bundled JS" solution in W3TC, too? (or whatever it's called)

As stated, I did face problems with the non-minified version of asp-*.js, too. I disabled the minified version, cleared out all the cached asp files, cleared the LiteSpeed cache, and tested it (CDN flushed, too, ofc.).

Let me know if you don't have a LiteSpeed instance running. I joined the Slack, btw, but I'm clearly the only person there. 
_With that said, I've previously started a full-stack LiteSpeed instance with WordPress and [LiteSpeed Cache](https://wordpress.org/plugins/litespeed-cache/) in Docker, if that's something you normally do._

**Comment by ernestmarcinko** [comment] 2024-08-02 13:35
I'm currently trying Litespeed, that does not care about the .min, it minifies and breaks it immediately. I'm checking if there is a regex or any other way.

**Comment by exetico** [comment] 2024-08-02 13:42
I'd really like if it's possible to keep using LiteSpeed Cache the normal way (bundled file, and still minified). But I'm not sure, if it's just a configuration tweak in your new esbuild configuration, or if it's more problematic than that.

I've used esbuild before, but I'm not doing any kind of development for WordPress, related to plugins and stuff like that. With that said, I'm (sort of) used to debugging in the LiteSpeed Cache env.

**Comment by ernestmarcinko** [comment] 2024-08-02 13:45
Got a solution for Litespeed in the meantime via `litespeed_optimize_js_excludes` hook. Unfortunately only full exclusion is possible from the bundle, it can't ignore only the minify step.

I have tried at least a 100 different esbuild configs, but no luck, re-minify always fails. I mean it shouldn't, but the cause should not be a minified input - but javascript minification is a pain on it's own.

**Comment by ernestmarcinko** [comment] 2024-08-02 13:59
Okay, Litespeed, WP Rocket, W3TC seem to be resolved. W3TC & WP Rocket can even bundle into one file, Litespeed can't.

Which other plugins should I test? I'm not a big minify user myself so I don't know them very well. Let me know :)

**Comment by exetico** [comment] 2024-08-02 14:07
_Just for my confirmation_;
As mentioned, LiteSpeed Cache also broke with the standard version (non-minified) version of the asp script, after it had been minified and combined with the LiteSpeed Cache Page Optimization solution.

That's still a problem :)?

1) Changed to the non-minified version of the asp script
2) Removed every asp script in the cache dir
3) Confirmed that the new asp file (`asp-0a562175.js`) was not minified
4) Jumped to the Tuning > JS Excludes and removed `cache/asp/`
5) Removed the caching I had in LiteSpeed Cache
5) Flushed my CDN Cache
6) Saw the script break again, after LiteSpeed Cache minified it

Is that fixed?

With the old build of .12, I could both bundle the acp script, and minify it with LiteSpeed Cache, even though I used the minified version of the ASP script.

I've personally not used other solutions than Litespeed Cache, WP Rocket and W3TC.

**Comment by ernestmarcinko** [comment] 2024-08-02 14:10
Update: Autoptimize, SG Optimizer, WP-Optimize all work with the `.min` solution.

> _Just for my confirmation_; As mentioned, LiteSpeed Cache also broke with the standard version (non-minified) version of the asp script, after it had been minified and combined with the LiteSpeed Cache Page Optimization solution.
> 
> That's still a problem :)?
> 
> 1. Changed to the non-minified version of the asp script
> 2. Removed every asp script in the cache dir
> 3. Confirmed that the new asp file (`asp-0a562175.js`) was not minified
> 4. Jumped to the Tuning > JS Excludes and removed `cache/asp/`
> 5. Removed the caching I had in LiteSpeed Cache
> 6. Flushed my CDN Cache
> 7. Saw the script break again, after LiteSpeed Cache minified it
> 
> Is that fixed?

On my end it's okay - but that highly depends on what's within the whole bundle. If Litespeed minifies after concat (which makes sense), then it's different for every single setup.

**Comment by ernestmarcinko** [comment] 2024-08-02 14:14
> Update: Autoptimize, SG Optimizer, WP-Optimize all work with the `.min` solution.
> 
> > _Just for my confirmation_; As mentioned, LiteSpeed Cache also broke with the standard version (non-minified) version of the asp script, after it had been minified and combined with the LiteSpeed Cache Page Optimization solution.
> > That's still a problem :)?
> > 
> > 1. Changed to the non-minified version of the asp script
> > 2. Removed every asp script in the cache dir
> > 3. Confirmed that the new asp file (`asp-0a562175.js`) was not minified
> > 4. Jumped to the Tuning > JS Excludes and removed `cache/asp/`
> > 5. Removed the caching I had in LiteSpeed Cache
> > 6. Flushed my CDN Cache
> > 7. Saw the script break again, after LiteSpeed Cache minified it
> > 
> > Is that fixed?
> 
> On my end it's okay - but that highly depends on what's within the whole bundle. If Litespeed minifies after concat (which makes sense), then it's different for every single setup.

Correction, it does not work, I didn't delete the correct folder. I'm afraid that will not give in :(

**Comment by exetico** [comment] 2024-08-02 14:15
That's my point, and that have not been a problem on previous versions. I guess I just have to exclude the asp script at this point, but I'm not that happy with the solution. 

I've not checked if LiteSpeed Cache are first bundling up scripts, and hereafter, minifying them.

It sounds like I need to bring up a staging env., just to see what's causing the problem. With that said; I've linked to pastebin in one of my emails, but, I understand that it doesn't help much, now that its just a esbuild configuration (or solution) thing; nothing in your source code.

**Comment by exetico** [comment] 2024-08-02 14:16
> Correction, it does not work, I didn't delete the correct folder. I'm afraid that will not give in :(

If so, we need to find out what's going on. I've used the LiteSpeed Cache Slack channel before, so, I'll give them a hint, too. However, I'd suggest you try and ask them, too. You know, as the main developer 😄.

Update: 
Posted here 👉  https://golitespeed.slack.com/archives/C3RJHNBTQ/p1722608802507639

**Comment by ernestmarcinko** [comment] 2024-08-02 14:36
Okays, thanks! The bundle is okay for sure, I was looking at the errors, it was basically missing parts of code (few parenthesis as far as I was able to decode).

The best possible approach in my optinion is to programmatically exclude, as the issue is not directly with this plugin, but with the minify itself, which unfortuantely does happen from time to time.
If there is (or going to be) a hook to simply exclude the files from minify but not from concat/bundle into one file, I'm more than happy to code that in.

**Comment by exetico** [comment] 2024-08-02 14:39
I'm still wondering if all esbuilds are facing the same issues with LiteSpeed after minification and bundling, or if this is specific to a package in your bundle. I didn't spend time on looking into that part. Did you check that, yourself? I mean, if it's your source-code, or another npm package.

**Comment by ernestmarcinko** [comment] 2024-08-02 14:40
WAIT A SECOND 

Adding the .min actually fixes Litespeed Cache!
That's why it was working!!! I thought it was because of non-minified, but it's because of the minified source! YAY

![image](https://github.com/user-attachments/assets/b5d73a19-9995-4d41-8656-ae921122260c)

**Comment by ernestmarcinko** [comment] 2024-08-02 14:51
@exetico I have sent you an invite to beta repo, I will try to push an RC tomorrow.

@kroix do you also want an invite to beta test?

**Comment by kroix** [comment] 2024-08-02 14:57
@ernestmarcinko No, thanks. 
I am very weak in development and debugging (I don't know how to do it at all), and I am not ready to conduct experiments on a working site. It is too important for me) I am waiting for the bug in the plugin to be fixed so that I can use the site in the previous configuration. If this does not work, the solution with disabling JavaScript minification will suit me. At least some solution.
Should I close this thread or mark something? This is my first and only post on GitHub.

**Comment by ernestmarcinko** [comment] 2024-08-02 14:59
> @ernestmarcinko No, thanks. I am very weak in development and debugging (I don't know how to do it at all), and I am not ready to conduct experiments on a working site. It is too important for me) I am waiting for the bug in the plugin to be fixed so that I can use the site in the previous configuration. If this does not work, the solution with disabling JavaScript minification will suit me. At least some solution. Should I close this thread or mark something? This is my first and only post on GitHub.

No problem :) It's most likely to be fixed within the first half of next week. I already seem to have a working solution + a few known bugs have to be fixed. Tomorrow I will post a beta release, then if this issue is fixed I will release as soon as possible.

**Comment by exetico** [comment] 2024-08-02 15:53
@ernestmarcinko Interesting. I'll give it a go once ready. Feel free to tag me in the  merge of the PR, if that's how you're working with GitHub. I'll accept the invite soon.

But... I'm a bit confused, after receiving inputs from the LiteSpeed Cache team:
https://golitespeed.slack.com/archives/C3RJHNBTQ/p1722614413864349?thread_ts=1722608802.507639&cid=C3RJHNBTQ

They state that adding "min" shouldn't change a thing. Are you sure, that you actually did things, like you told in the previous post? 😁 Cached ASP and caching from LTC are interesting things to play with in combination, and  can outplay even the best devs, from time to time 😉.

With that said; I only use ASP on a single prod-site, where it broke things today. Testing a beta release would only be possible, if you can confirm that no other risks should be expected.

**Comment by ernestmarcinko** [comment] 2024-08-03 12:43
I merged a PR related to this, I will post a beta release on the [beta repository](https://github.com/ernestmarcinko/ajax-search-pro-beta) in a couple of hours to test.

**Comment by ernestmarcinko** [comment] 2024-08-03 12:56
> Are you sure, that you actually did things, like you told in the previous post? 😁 Cached ASP and caching from LTC are interesting things to play with in combination, and can outplay even the best devs, from time to time 😉.

It's 100%, I just tried again. I think they may have forgotten about this feature, or there is a built in check within the minifier to check the filenames. Either way, it's a good thing, it's how it supposed to be. See tests below.

## Test 1 - with .min.js as filename

Litespeed minify/combine disabled:

![image](https://github.com/user-attachments/assets/2cd5d4ae-7108-4fc5-ba45-277c46f950ed)

Litespeed enabled:
![image](https://github.com/user-attachments/assets/90a874ac-a896-4a5f-9c6a-7ec9f112f0da)

## Test 2 - withOUT .min.js as filename (as it is now)

Litespeed disabled:

![image](https://github.com/user-attachments/assets/98b87d25-0d67-4789-be19-6d990a773e4f)

Litespeed enabled:

![image](https://github.com/user-attachments/assets/6a7c6150-aaf3-43ac-b541-a0101eb561d8)

This is simply great, you will have a chance to test it in a few hours :)

**Comment by ernestmarcinko** [comment] 2024-08-03 15:25
Beta 4.26.14 is ready to test [here](https://github.com/ernestmarcinko/ajax-search-pro-beta/releases/tag/4.26.14-rc1).

**Comment by exetico** [comment] 2024-08-05 07:54
The new minified version works with my setup, too, also with "JS Combine". I've submitted another issue, not related to this, I noticed while testing the beta-release (the issues with Rocket Loader are not related to this, though).

**Closed as completed** 2024-08-05 12:59 UTC
Labels: bug

**Comment by kroix** [comment] 2024-08-06 07:47
@ernestmarcinko
After the update everything works fine.
Minification is enabled (minify and combine). Thanks for the great plugin and for solving the problem!
